package com.onionscape.game;

import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.Texture.TextureFilter;

import storage.Storage;

public class TextureManager {
	private static TextureManager instance = new TextureManager();
	
	public static Texture inventorySlotTexture = Storage.assetManager.get("InventorySlot.png", Texture.class);
	public static Texture ironGreataxeTexture = Storage.assetManager.get("weapons/inventory/IronGreataxe.png", Texture.class);
	public static Texture ironShieldTexture = Storage.assetManager.get("weapons/inventory/IronShield.png", Texture.class);
	public static Texture ironAxeTexture = Storage.assetManager.get("weapons/inventory/IronAxe.png", Texture.class);
	public static Texture woodenGreataxeTexture = Storage.assetManager.get("weapons/inventory/WoodenGreataxe.png", Texture.class);
	public static Texture ironHelmetTexture = Storage.assetManager.get("armor/inventory/IronHelmet.png", Texture.class);
	public static Texture ironChestTexture = Storage.assetManager.get("armor/inventory/IronChest.png", Texture.class);
	public static Texture ironBootsTexture = Storage.assetManager.get("armor/inventory/IronBoots.png", Texture.class);
	public static Texture woodenShieldTexture = Storage.assetManager.get("weapons/inventory/WoodenShield.png", Texture.class);
	public static Texture healthPotionTexture = Storage.assetManager.get("items/HealthPotion.png", Texture.class);
	public static Texture bombTexture = Storage.assetManager.get("items/Bomb.png", Texture.class);
	public static Texture knifeTexture = Storage.assetManager.get("items/ThrowingKnife.png", Texture.class);
	public static Texture apTexture = Storage.assetManager.get("items/AttackBoost.png", Texture.class);
	public static Texture dpTexture = Storage.assetManager.get("items/DefenseBoost.png", Texture.class);
	public static Texture hpTexture = Storage.assetManager.get("items/HealthBoost.png", Texture.class);
	public static Texture expTexture = Storage.assetManager.get("items/ExperienceBoost.png", Texture.class);
	public static Texture swingTexture = Storage.assetManager.get("abilities/Swing.png", Texture.class);
	public static Texture rendTexture = Storage.assetManager.get("abilities/Rend.png", Texture.class);
	public static Texture whirlwindTexture = Storage.assetManager.get("abilities/Whirlwind.png", Texture.class);
	public static Texture groundBreakerTexture = Storage.assetManager.get("abilities/GroundBreaker.png", Texture.class);
	public static Texture bashTexture = Storage.assetManager.get("abilities/Bash.png", Texture.class);
	public static Texture barrierTexture = Storage.assetManager.get("abilities/Barrier.png", Texture.class);
	public static Texture hardenTexture = Storage.assetManager.get("abilities/Harden.png", Texture.class);
	public static Texture mendTexture = Storage.assetManager.get("abilities/Mend.png", Texture.class);
	public static Texture hiltBashTexture = Storage.assetManager.get("abilities/HiltBash.png", Texture.class);
	public static Texture barbedArmorTexture = Storage.assetManager.get("abilities/BarbedArmor.png", Texture.class);
	public static Texture enrageTexture = Storage.assetManager.get("abilities/Enrage.png", Texture.class);
	public static Texture riposteTexture = Storage.assetManager.get("abilities/Riposte.png", Texture.class);
	public static Texture stabTexture = Storage.assetManager.get("abilities/Stab.png", Texture.class);
	public static Texture decapitateTexture = Storage.assetManager.get("abilities/Decapitate.png", Texture.class);
	public static Texture onionTexture = Storage.assetManager.get("player/Onion.png", Texture.class);
	public static Texture eIronGreataxeTexture = Storage.assetManager.get("weapons/equipped/IronGreataxe.png", Texture.class);
	public static Texture eWoodenGreataxeTexture = Storage.assetManager.get("weapons/equipped/WoodenGreataxe.png", Texture.class);
	public static Texture woodenAxeTexture = Storage.assetManager.get("weapons/inventory/WoodenAxe.png", Texture.class);	
	public static Texture eWoodenAxeTexture = Storage.assetManager.get("weapons/equipped/WoodenAxe.png", Texture.class);
	public static Texture eIronAxeTexture = Storage.assetManager.get("weapons/equipped/IronAxe.png", Texture.class);
	public static Texture eIronShieldTexture = Storage.assetManager.get("weapons/equipped/IronShield.png", Texture.class);
	public static Texture eWoodenShieldTexture = Storage.assetManager.get("weapons/equipped/WoodenShield.png", Texture.class);		
	public static Texture eIronHelmetTexture = Storage.assetManager.get("armor/equipped/IronHelmet.png", Texture.class);		
	public static Texture eIronChestTexture = Storage.assetManager.get("armor/equipped/IronChest.png", Texture.class);		
	public static Texture eIronBootsTexture = Storage.assetManager.get("armor/equipped/IronBoots.png", Texture.class);		
	public static Texture eBronzeHelmetTexture = Storage.assetManager.get("armor/equipped/BronzeHelmet.png", Texture.class);		
	public static Texture eBronzeChestTexture = Storage.assetManager.get("armor/equipped/BronzeChest.png", Texture.class);		
	public static Texture eBronzeBootsTexture = Storage.assetManager.get("armor/equipped/BronzeBoots.png", Texture.class);	
	public static Texture eSteelHelmetTexture = Storage.assetManager.get("armor/equipped/SteelHelmet.png", Texture.class);		
	public static Texture eSteelChestTexture = Storage.assetManager.get("armor/equipped/SteelChest.png", Texture.class);		
	public static Texture eSteelBootsTexture = Storage.assetManager.get("armor/equipped/SteelBoots.png", Texture.class);
	public static Texture bronzeHelmetTexture = Storage.assetManager.get("armor/inventory/BronzeHelmet.png", Texture.class);
	public static Texture bronzeChestTexture = Storage.assetManager.get("armor/inventory/BronzeChest.png", Texture.class);
	public static Texture bronzeBootsTexture = Storage.assetManager.get("armor/inventory/BronzeBoots.png", Texture.class);
	public static Texture steelHelmetTexture = Storage.assetManager.get("armor/inventory/SteelHelmet.png", Texture.class);
	public static Texture steelChestTexture = Storage.assetManager.get("armor/inventory/SteelChest.png", Texture.class);
	public static Texture steelBootsTexture = Storage.assetManager.get("armor/inventory/SteelBoots.png", Texture.class);
	public static Texture bronzeGreataxeTexture = Storage.assetManager.get("weapons/inventory/BronzeGreataxe.png", Texture.class);
	public static Texture bronzeShieldTexture = Storage.assetManager.get("weapons/inventory/BronzeShield.png", Texture.class);
	public static Texture bronzeAxeTexture = Storage.assetManager.get("weapons/inventory/BronzeAxe.png", Texture.class);
	public static Texture steelGreataxeTexture = Storage.assetManager.get("weapons/inventory/SteelGreataxe.png", Texture.class);
	public static Texture steelShieldTexture = Storage.assetManager.get("weapons/inventory/SteelShield.png", Texture.class);
	public static Texture steelAxeTexture = Storage.assetManager.get("weapons/inventory/SteelAxe.png", Texture.class);
	public static Texture eBronzeAxeTexture = Storage.assetManager.get("weapons/equipped/BronzeAxe.png", Texture.class);
	public static Texture eBronzeShieldTexture = Storage.assetManager.get("weapons/equipped/BronzeShield.png", Texture.class);
	public static Texture eBronzeGreataxeTexture = Storage.assetManager.get("weapons/equipped/BronzeGreataxe.png", Texture.class);
	public static Texture eSteelAxeTexture = Storage.assetManager.get("weapons/equipped/SteelAxe.png", Texture.class);
	public static Texture eSteelShieldTexture = Storage.assetManager.get("weapons/equipped/SteelShield.png", Texture.class);
	public static Texture eSteelGreataxeTexture = Storage.assetManager.get("weapons/equipped/SteelGreataxe.png", Texture.class);
	public static Texture abilityCardTexture = Storage.assetManager.get("items/CardLarge.png", Texture.class);
	public static Texture gearCardTexture = Storage.assetManager.get("items/CardSmall.png", Texture.class);
	public static Texture abilityRefillTexture = Storage.assetManager.get("items/AbilityRefillPotion.png", Texture.class);
	
	public static TextureManager getInstance() {
        return instance;
    }
	
	public void smoothFilter(){
		inventorySlotTexture.setFilter(TextureFilter.Linear,TextureFilter.Nearest);
		abilityRefillTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eIronGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eWoodenGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eIronAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eWoodenAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eWoodenShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eIronShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		onionTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		ironAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		woodenAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		ironGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		woodenGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		ironShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		woodenShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		healthPotionTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bombTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		knifeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		apTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		dpTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		hpTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		expTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		swingTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		rendTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		whirlwindTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		groundBreakerTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bashTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		barrierTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		hardenTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		mendTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		hiltBashTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		barbedArmorTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		enrageTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		riposteTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		stabTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		decapitateTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		ironHelmetTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		ironChestTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		ironBootsTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eIronHelmetTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eIronChestTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eIronBootsTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);		
		eBronzeHelmetTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);	
		eBronzeChestTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eBronzeBootsTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eSteelHelmetTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eSteelChestTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eSteelBootsTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bronzeHelmetTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bronzeChestTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bronzeBootsTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		steelHelmetTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		steelChestTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		steelBootsTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bronzeGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bronzeShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		bronzeAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		steelGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		steelShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		steelAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eBronzeAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eBronzeShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eBronzeGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eSteelAxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eSteelShieldTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		eSteelGreataxeTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		abilityCardTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
		gearCardTexture.setFilter(TextureFilter.MipMap,TextureFilter.Nearest);
	}
}
